server:
  port: 8601


file:
  upload:
    path: /root/hyblog/
  reflect:
    path: http://124.70.200.174:81/img/
#阿里大于
templateCode: SMS_243246372 #短信模板编号
signName: 云衡博客
#项目名称
PROJECT_NAME: 云衡博客S_243246372 #短信模板编号

# 邮箱验证
moguBlog:
  email: tanlin0421@163.com

# 蘑菇博客登录默认密码
DEFAULE_PWD: hy2020

#博客相关配置
BLOG:
  HOT_COUNT: 5 #热门博客数量
  NEW_COUNT: 15 #最新博客数据
  FIRST_COUNT: 5 #一级推荐
  SECOND_COUNT: 2 #二级推荐
  THIRD_COUNT: 3 #三级推荐
  FOURTH_COUNT: 5 #四级推荐




spring:
  rabbitmq:
    host: www.tanliny.xyz
    port: 5672
  security:
    user:
      name: guest
      password: guest
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  elasticsearch:
    rest:
      uris: www.tanliny.xyz:9200
  datasource:
    username: tanlin
    password: tanlin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.tanliny.xyz:3306/hy_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    # 初始化大小，最小，最大
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 5
    maxActive: 200

    #连接等待超时时间
    maxWait: 60000

    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000

    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000

    validationQuery: SELECT 1 FROM DUAL

    dbcp:
      remove-abandoned: true
      #泄露的连接可以被删除的超时时间（秒），该值应设置为应用程序查询可能执行的最长时间
      remove-abandoned-timeout: 180

    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: www.tanliny.xyz
    port: 6379
    password: '123456'

  cloud:
    inetutils:
      ignored-interfaces: eth.*
    nacos:
      discovery:
        server-addr: www.tanliny.xyz:8848
        ip: 124.70.200.174
      config:
        file-extension: yaml
        group: hyblog

    # 配置Sentinel流控
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: www.tanliny.xyz:8858
        #默认8719端口,如果被占用会向上扫描。
        port: 8858


##jwt配置
tokenHead: bearer_
tokenHeader: Authorization
isRememberMeExpiresSecond: 259200 #记住账号为3天有效
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: hyblog
  expiresSecond: 3600  #1个小时 3600
  refreshSecond: 300 # 刷新token的时间 5分钟