server:
  port: 8602


file:
  upload:
    path: /root/hyblog/
  reflect:
    path: http://124.70.200.174:81/img/

spring:
  application:
    name: hy-picture
  elasticsearch:
    rest:
      uris: www.tanliny.xyz:9200
  datasource:
    username: tanlin
    password: tanlin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.tanliny.xyz:3306/hy_picture?serverTimezone=UTC&characterEncoding=UTF-8
  redis:
    host: www.tanliny.xyz
    port: 6379
    password: '123456'

  cloud:
    # 配置Sentinel流控
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: www.tanliny.xyz:8858
        #默认8719端口,如果被占用会向上扫描。
        port: 8858
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 修改单次文件上传文件大小不能超过100MB
      max-request-size: 500MB  # 设置单次文件请求总大小不能超过500MB
