server:
  port: 8605

spring:
  elasticsearch:
    rest:
      uris: http://www.tanliny.xyz:9200
  application:
    name: hy-search
  cloud:
    # 配置Sentinel流控
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: www.tanliny.xyz:8858
        #默认8719端口,如果被占用会向上扫描。
        port: 8858
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: tanlin
    password: tanlin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.tanliny.xyz:3306/hy_blog?serverTimezone=UTC&characterEncoding=UTF-8