
#阿里大于
templateCode: SMS_243246372 #短信模板编号

signName: 云衡博客
# 项目英文名
PROJECT_NAME_EN: yhBlog
#项目名称
PROJECT_NAME: 云衡博客

file:
  upload:
    path: /root/hyblog/
  reflect:
    path: http://124.70.200.174:81/img/
data:
  # 门户页面
  webSite:
    url: http://localhost:9527/#/
  web:
    url: http://127.0.0.1:8603



# 蘑菇博客登录默认密码
DEFAULE_PWD: hy2018

#请求限制参数
request-limit:
  start: false # 是否开启请求限制，默认关闭
  amount: 100 # 100次
  time: 60000 # 1分钟

#博客相关配置
BLOG:
  HOT_COUNT: 5 #热门博客数量
  HOT_TAG_COUNT: 20 #热门标签数量
  FRIENDLY_LINK_COUNT: 20 #友情链接数
  NEW_COUNT: 15 #最新博客数据
  FIRST_COUNT: 5 #一级推荐
  SECOND_COUNT: 2 #二级推荐
  THIRD_COUNT: 3 #三级推荐
  FOURTH_COUNT: 5 #四级推荐
  USER_TOKEN_SURVIVAL_TIME: 24 # toekn令牌存活时间, 1天

  # 原创模板
  ORIGINAL_TEMPLATE: "test"
  # 转载模板
  REPRINTED_TEMPLATE: "test"

spring:
  elasticsearch:
    rest:
      uris: www.tanliny.xyz:9200
  datasource:
    username: tanlin
    password: tanlin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.tanliny.xyz:3306/hy_blog?serverTimezone=UTC&characterEncoding=UTF-8
    # 初始化大小，最小，最大
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 50

    #连接等待超时时间
    maxWait: 60000

    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000

    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000

    dbcp:
      remove-abandoned: true
      #泄露的连接可以被删除的超时时间（秒），该值应设置为应用程序查询可能执行的最长时间
      remove-abandoned-timeout: 180

    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: www.tanliny.xyz
    port: 6379
    password: '123456'
  rabbitmq:
    host: www.tanliny.xyz
    port: 5672

  cloud:
    # 配置Sentinel流控
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: www.tanliny.xyz:8858
        #默认8719端口,如果被占用会向上扫描。
        port: 8858
justAuth:
  clientId:
    gitee: ec2dba332701caa209935512c69fc7962530b8619acd9b6cb03106a7c13c1c5e
    github: c99bfe31f8774ec8e242
    qq: 56262465  # 改成自己的
  clientSecret:
    gitee: 993930de16b61b8146f7d30c693afd328b4d42116cf2da748f275077e4ef5e47
    github: ec088d14ab8076e2beed58fcb95e37a0fc586618
    qq: 56262465 # 改成自己的

##jwt配置
tokenHead: bearer_
tokenHeader: Authorization
isRememberMeExpiresSecond: 259200 #记住账号为3天有效
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: hyblog
  expiresSecond: 86400  #24个小时 3600
  refreshSecond: 300 # 刷新token的时间 5分钟